# Generated by Django 5.0.2 on 2024-06-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0025_user_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
