# Generated by Django 5.0.2 on 2024-06-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0026_user_last_active_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='score_l',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='match',
            name='score_w',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
