# Generated by Django 5.0.2 on 2024-06-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0027_match_score_l_match_score_w'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rival',
            field=models.CharField(default='Guest', max_length=50),
        ),
    ]
